I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script másolata.rpy", line 9, in script
    "CSUHAJJA [v]"
KeyError: u'v'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script másolata.rpy", line 9, in script
    "CSUHAJJA [v]"
  File "C:\jóságok\progik\renpy-7.2.2-sdk\renpy\ast.py", line 694, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "C:\jóságok\progik\renpy-7.2.2-sdk\renpy\exports.py", line 1322, in say
    who(what, *args, **kwargs)
  File "C:\jóságok\progik\renpy-7.2.2-sdk\renpy\character.py", line 1114, in __call__
    what = what_pattern.replace("[what]", sub(what, translate=True))
  File "C:\jóságok\progik\renpy-7.2.2-sdk\renpy\character.py", line 1103, in sub
    return renpy.substitutions.substitute(s, scope=scope, force=force, translate=translate)[0]
  File "C:\jóságok\progik\renpy-7.2.2-sdk\renpy\substitutions.py", line 244, in substitute
    s = formatter.vformat(s, (), kwargs)
  File "/home/tom/ab/x64lucid-deps/install/lib/python2.7/string.py", line 563, in vformat
  File "/home/tom/ab/x64lucid-deps/install/lib/python2.7/string.py", line 585, in _vformat
  File "/home/tom/ab/x64lucid-deps/install/lib/python2.7/string.py", line 646, in get_field
  File "/home/tom/ab/x64lucid-deps/install/lib/python2.7/string.py", line 605, in get_value
KeyError: u'v'

Windows-8-6.2.9200
Ren'Py 7.2.2.491
A NYUGAT 1.0
Thu May 23 16:16:02 2019
